server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: analytics-service
          uri: http://analytics:8080
          predicates:
            - Path=/api/v1/analytics/**
        - id: core-service
          uri: http://api:8080
          predicates:
            - Path=/api/v1/**
